import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Auto-generated by ORVAL.
    "lib/api/generated.ts",
  ]),
  {
    rules: {
      // Next 16 / React 19 introduced this rule. We rely on the classic
      // "fetch on mount via useEffect" pattern (no React Query) and intentionally
      // synchronize external (REST) state via setState callbacks.
      // Downgrade to warn rather than error.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
]);

export default eslintConfig;
